[book]
authors = ["svartalf"]
language = "en"
multilingual = false
src = "src"
title = "heim"
create-missing = false

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/heim-rs/book"